import HautevilleHouse.AnalyticalChemistryMicrofluidicsAnalyticalCanonicalLaneLean.AdmissibleClass
import HautevilleHouse.AnalyticalChemistryMicrofluidicsAnalyticalCanonicalLaneLean.BridgeLemmas
import HautevilleHouse.AnalyticalChemistryMicrofluidicsAnalyticalCanonicalLaneLean.GateLemmas
import HautevilleHouse.AnalyticalChemistryMicrofluidicsAnalyticalCanonicalLaneLean.FlowFieldLayer
import HautevilleHouse.AnalyticalChemistryMicrofluidicsAnalyticalCanonicalLaneLean.NavierStokesPersistenceLayer
import HautevilleHouse.AnalyticalChemistryMicrofluidicsAnalyticalCanonicalLaneLean.MicrofluidicChannelLayer
import HautevilleHouse.AnalyticalChemistryMicrofluidicsAnalyticalCanonicalLaneLean.FinalTheorem